version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-edu_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  edu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edu
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-80}:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-edu_db}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - SERVER_PORT=80
      - DDL_AUTO=validate
      - FLYWAY_ENABLED=true
    depends_on:
      - postgres-db

volumes:
  postgres_data: